Repository jenkinsci/ldap-plugin, pull requests merged in 2020-11, with the labels that each got.

#49 Build against Spring Security
  Jenkinsfile
  pom.xml
  src/main/java/hudson/security/LDAPSecurityRealm.java
  src/main/java/jenkins/security/plugins/ldap/BindAuthenticator2.java
  src/main/java/jenkins/security/plugins/ldap/FromGroupSearchLDAPGroupMembershipStrategy.java
  src/main/java/jenkins/security/plugins/ldap/FromUserRecordLDAPGroupMembershipStrategy.java
  src/main/java/jenkins/security/plugins/ldap/LDAPConfiguration.java
  src/main/java/jenkins/security/plugins/ldap/LDAPExtendedTemplate.java
  src/main/java/jenkins/security/plugins/ldap/LDAPGroupMembershipStrategy.java
  src/main/java/jenkins/security/plugins/ldap/LdapEntryMapper.java
  src/main/java/jenkins/security/plugins/ldap/SetContextClassLoader.java
  src/test/java/hudson/security/LDAPEmbeddedTest.java
  src/test/java/hudson/security/LDAPSecurityRealmTest.java
  src/test/java/hudson/security/LdapMultiEmbedded2Test.java
  src/test/java/hudson/security/LdapMultiEmbeddedTest.java
  src/test/java/hudson/security/docker/MultiServerTest.java
  src/test/java/hudson/security/docker/PlanetExpressTest.java
  src/test/java/jenkins/security/plugins/ldap/LDAPExtendedTemplateTest.java
  src/test/resources/hudson/security/LDAPSecurityRealmTest/compatAndConfig/config.xml
Labels: major-enhancement

#52 Spring cleaning
  src/main/java/hudson/security/LDAPSecurityRealm.java
  src/main/java/jenkins/security/plugins/ldap/FromGroupSearchLDAPGroupMembershipStrategy.java
  src/main/java/jenkins/security/plugins/ldap/LDAPConfiguration.java
  src/test/java/hudson/security/LDAPSecurityRealmTest.java
Labels: chore, enhancement, removed

#59 [JENKINS-55813] Add support for LDAP password policy attributes (account locking)
  README.md
  pom.xml
  src/main/java/hudson/security/GeneralizedTime.java
  src/main/java/hudson/security/LDAPSecurityRealm.java
  src/main/java/hudson/security/UserAttributesHelper.java
  src/main/java/jenkins/security/plugins/ldap/LDAPConfiguration.java
  src/test/java/hudson/security/LDAPEmbeddedTest.java
  src/test/java/hudson/security/docker/MultiServerTest.java
  src/test/java/hudson/security/docker/PlanetExpressTest.java
  src/test/resources/hudson/security/planetexpressWithPPolicy.ldif
Labels: enhancement
