Repository jenkinsci/ldap-plugin, pull requests merged in 2020-03, with the labels that each got.

#40 Configuration as Code compatibility tests
  README.md
  pom.xml
  src/test/java/jenkins/security/plugins/ldap/CasCTest.java
  src/test/java/jenkins/security/plugins/ldap/CascSecurityRealmTest.java
  src/test/resources/jenkins/security/plugins/ldap/LDAPSecurityRealmTestNoSecret.yml
  src/test/resources/jenkins/security/plugins/ldap/LDAPSecurityRealmTestNoSecretExpected.yml
  src/test/resources/jenkins/security/plugins/ldap/casc.yml
Labels: chore

#29 Spelling
  README.md
  src/main/java/hudson/security/LDAPSecurityRealm.java
  src/main/java/jenkins/security/plugins/ldap/LDAPConfiguration.java
Labels: documentation

#38 Migrate docs from wiki to github
  CHANGELOG.md
  README.md
  docs/images/Screen_Shot_2014-07-15_at_10.19.14.png
  docs/images/Screen_Shot_2014-07-15_at_10.19.23.png
  docs/images/Screen_Shot_2017-05-02_at_09.52.20.png
  docs/images/test-ldap-dialog.png
  pom.xml
Labels: chore, documentation
