Repository jenkinsci/ldap-plugin, pull requests merged in 2020-09, with the labels that each got.

#46 Remove use of BeanBuilder; construct components in Java
  src/main/java/hudson/security/LDAPSecurityRealm.java
  src/main/java/jenkins/security/plugins/ldap/LDAPConfiguration.java
  src/main/java/org/acegisecurity/providers/ldap/authenticator/BindAuthenticator2.java
  src/main/resources/hudson/security/LDAPBindSecurityRealm.groovy
  src/main/resources/hudson/security/LDAPSecurityRealm/config.jelly
  src/main/resources/hudson/security/LDAPSecurityRealm/config.properties
  src/test/java/hudson/security/LDAPSecurityRealmTest.java
  src/test/java/jenkins/security/plugins/ldap/LDAPConfigurationTest.java
Labels: removed

#48 Compatibility with Spring Security
  .mvn/extensions.xml
  .mvn/maven.config
  Jenkinsfile
  pom.xml
Labels: dependencies

#51 Removing some documentation related to BeanBuilder
  README.md
  src/main/java/hudson/security/LDAPSecurityRealm.java
  src/main/java/jenkins/security/plugins/ldap/FromGroupSearchLDAPGroupMembershipStrategy.java
  src/main/resources/hudson/security/LDAPSecurityRealm/help-groupMembershipFilter.html
  src/main/resources/jenkins/security/plugins/ldap/LDAPConfiguration/help-groupSearchBase.html
Labels: documentation

#44 Tip for avoid foward slash character in the Organization Units
  README.md
Labels: documentation
