Repository jenkinsci/ldap-plugin, pull requests merged in 2021-04, with the labels that each got.

#81 [JENKINS-65117] fix the case sensitivity in the test method for the DN
  src/main/java/hudson/security/LDAPSecurityRealm.java
  src/main/java/jenkins/security/plugins/ldap/LDAPExtendedTemplate.java
  src/main/resources/jenkins/security/plugins/ldap/Messages.properties
Labels: bug

#33 Migrate into localization-zh-cn-plugin
  src/main/resources/hudson/security/LDAPSecurityRealm/config_zh_CN.properties
Labels: documentation

#78 Freshen up realistic tests
  pom.xml
  src/main/resources/index.jelly
  src/test/java/hudson/security/docker/MultiServerTest.java
  src/test/java/hudson/security/docker/PlanetExpressTest.java
  src/test/resources/hudson/security/docker/PlanetExpressTest/PlanetExpress/Dockerfile
Labels: dependencies, tests

#82 Add CODEOWNERS
  .github/CODEOWNERS
Labels: chore

#89 [JENKINS-65398] terminology update
  README.md
  src/main/resources/hudson/security/LDAPSecurityRealm/help-cache.html
Labels: documentation

#85 Include RootDN in doCheckServer
  src/main/java/hudson/security/LDAPSecurityRealm.java
  src/main/java/jenkins/security/plugins/ldap/LDAPConfiguration.java
Labels: bug
