Repository jenkinsci/ldap-plugin, pull requests merged in 2023-01, with the labels that each got.

#211 Adapt test to advanced component change in core
  src/test/java/hudson/security/LDAPSecurityRealmTest.java
Labels: tests

#207 Slightly improve README.md formatting
  README.md
Labels: documentation

#174 Use encoding of the request
  src/main/java/hudson/security/LDAPSecurityRealm.java
Labels: bug

#213 enable cd
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/cd.yaml
  .github/workflows/release-drafter.yml
  .mvn/maven.config
  CHANGELOG.md
  pom.xml
Labels: internal
