Repository jenkinsci/ldap-plugin, pull requests merged in 2024-10, with the labels that each got.

#277 Use new dialog design for validation dialog
  src/main/resources/jenkins/security/plugins/ldap/validation/validate.jelly
  src/main/resources/jenkins/security/plugins/ldap/validation/validate/validate.js
  src/main/resources/jenkins/security/plugins/ldap/validation/validateButton.js
  src/main/resources/jenkins/security/plugins/ldap/validation/validateButtonOnClick.js
  src/test/java/hudson/security/LDAPEmbeddedTest.java
Labels: enhancement

#303 Update plugin parent POM to latest
  pom.xml
Labels: dependencies, java

#311 Require 2.479.1 LTS or newer
  pom.xml
Labels: skip-changelog
